name: lawimmunity
description: LawImmunnity Application to record live videos and share with freinds and family

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^3.0.1
#  widgetbook_annotation: ^2.1.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  firebase_auth: ^3.4.2
  country_code_picker: ^2.0.2
  auto_size_text: ^3.0.0
  fluttertoast: ^8.0.9
  timeago: ^3.2.2
  get_it: ^7.2.0
  http: ^0.13.4
  flutter_background_geolocation: ^4.7.0
  background_geolocation_firebase: ^1.0.0
  flutter_map: ^1.1.0
  enx_flutter_plugin: ^2.1.2
  permission_handler: ^10.0.0
  firebase_messaging: ^12.0.0
  flutter_local_notifications: ^9.7.0
  cloud_firestore: ^3.3.0
  dio: ^4.0.6
#  fijkplayer: ^0.10.1
  path_provider: ^2.0.11
  video: ^0.0.1
  webview_flutter_plus: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  widgetbook: ^2.4.1
  widgetbook_generator: ^2.4.1


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/disconnect.png
    - assets/mute_audio.png
    - assets/unmute_audio.png
    - assets/unmute_video.png
    - assets/camera_switch.png
    - assets/mute_video.png
    - assets/mute_speaker.png
    - assets/unmute_speaker.png

#  fonts:
#    - family: Roboto
#      fonts:
#        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
#          weight: 100
#        - asset: assets/fonts/Roboto/Roboto-Light.ttf
#          weight: 300
#        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/Roboto/Roboto-Black.ttf
#          weight: 900
#
#    - family: Calistoga
#      fonts:
#        - asset: assets/fonts/Calistoga/Calistoga-Regular.ttf
#          weight: 400

flutter_intl:
  enabled: true
